# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=5)),
                ('shares', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TecStockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=b'', max_length=1)),
                ('last_name', models.CharField(default=b'', max_length=1)),
                ('earnt', models.FloatField(default=0)),
                ('spent', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockinfo.TecStockUser'),
        ),
        migrations.AlterUniqueTogether(
            name='stockinfo',
            unique_together=set([('user', 'stock')]),
        ),
    ]
