# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0002_auto_20160513_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecstockuser',
            name='email',
            field=models.CharField(default=b'', max_length=1),
        ),
    ]
