# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0005_auto_20160513_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='current_price',
            field=models.CharField(max_length=15),
        ),
    ]
