# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0006_auto_20160513_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='stock_name',
        ),
    ]
