# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0009_auto_20160514_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecstockuser',
            name='spent',
            field=models.FloatField(default=0),
        ),
    ]
