# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='shares',
            new_name='numbers',
        ),
        migrations.RemoveField(
            model_name='tecstockuser',
            name='earnt',
        ),
        migrations.RemoveField(
            model_name='tecstockuser',
            name='spent',
        ),
    ]
