# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0003_tecstockuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecstockuser',
            name='email',
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
