# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0004_auto_20160513_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='stock_name',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='tecstockuser',
            name='first_name',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='tecstockuser',
            name='last_name',
            field=models.CharField(default=b'', max_length=10),
        ),
    ]
