# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockinfo', '0008_tecstockuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
